// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCT01Ww2MzdehUTNnTL5AWyTY3rnhRCI',
    appId: '1:853638837349:web:1ee7ace34a3b0ec489028c',
    messagingSenderId: '853638837349',
    projectId: 'ecommerce-f3e6e',
    authDomain: 'ecommerce-f3e6e.firebaseapp.com',
    storageBucket: 'ecommerce-f3e6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoVRDyCUu2UPfrGICKsPV9AaZBzmjSqjU',
    appId: '1:853638837349:android:a7f4304378bc7f8289028c',
    messagingSenderId: '853638837349',
    projectId: 'ecommerce-f3e6e',
    storageBucket: 'ecommerce-f3e6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQOO7dka3k-k0vS0HqwxR7NzwJa0hCJg',
    appId: '1:853638837349:ios:40e8894af406988389028c',
    messagingSenderId: '853638837349',
    projectId: 'ecommerce-f3e6e',
    storageBucket: 'ecommerce-f3e6e.appspot.com',
    androidClientId: '853638837349-ctmesb12p5qiv5qrn18cikai3h95a3qo.apps.googleusercontent.com',
    iosClientId: '853638837349-2ugg0cgk38s3nk1dcn0jhl34bhpch1u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bmi',
  );

}